### ISSUE TITLE
Extcaves crash on server start

### ISSUE THREAD

**Issue by umbranium** [simibubi/Above-and-Beyond#105]
```
java.lang.IllegalStateException: Failed to resolve consumer event type: com.polyvalord.extcaves.ExtCaves$$Lambda$3893/0x0000000000000000@9130063c
	at net.minecraftforge.eventbus.EventBus.getEventClass(EventBus.java:220) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.checkNotGeneric(EventBus.java:162) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:179) ~[eventbus-4.0.0.jar:?]
	at com.polyvalord.extcaves.ExtCaves.<init>(ExtCaves.java:48) ~[extcaves:2.4]
	at java.lang.J9VMInternals.newInstanceImpl(Native Method) ~[?:1.8.0_282]
	at java.lang.Class.newInstance(Class.java:2015) ~[?:1.8.0_282]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) [forge:36.2]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3128/0x0000000000000000.run(Unknown Source) [forge:36.2]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) [forge:?]
	at net.minecraftforge.fml.ModContainer$$Lambda$3224/0x0000000000000000.run(Unknown Source) [forge:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_282]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_282]
```

Full logs: 
[latest.log](https://github.com/simibubi/Above-and-Beyond/files/7522728/latest.log)
[crash-2021-11-11_20.09.20-fml.txt](https://github.com/simibubi/Above-and-Beyond/files/7522744/crash-2021-11-11_20.09.20-fml.txt)

**Comment by umbranium** [comment]
resolved: specify jre 1.8 explicitly, in case jre 1.9 is set to java_home by accident
