### ISSUE TITLE
Crash generating autogenerated structure on surface

### ISSUE THREAD

**Issue by bvierra** [simibubi/Above-and-Beyond#219]
Create: Above and Beyond version: v1.2

Appears to be a crash relating to a generating a structure on the surface.

Have gone back to the area below the surface in a cave when it crashed as well as on the surface... never saw the generated structure before the crash.

[Full crash log
](https://paste.ee/p/PibgU)
Crash log head Full crash log:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 12/2/21 4:44 AM
Description: Feature placement

java.lang.NullPointerException: Feature placement
at com.simibubi.create.content.contraptions.base.GeneratingKineticTileEntity.updateGeneratedRotation(GeneratingKineticTileEntity.java:90) ~[create:mc1.16.5_v0.3.2g] {re:classloading}
at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_301] {}
at com.simibubi.create.foundation.block.ITE.withTileEntityDo(ITE.java:19) ~[create:mc1.16.5_v0.3.2g] {re:classloading}
at com.simibubi.create.content.contraptions.components.waterwheel.WaterWheelBlock.updateWheelSpeed(WaterWheelBlock.java:155) ~[create:mc1.16.5_v0.3.2g] {re:classloading}
at com.simibubi.create.content.contraptions.components.waterwheel.WaterWheelBlock.func_196271_a(WaterWheelBlock.java:77) ~[create:mc1.16.5_v0.3.2g] {re:classloading}
at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196956_a(AbstractBlock.java:657) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries.mixins.json:AbstractBlockMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:AbstractBlockStateMixin,pl:mixin:A}
at net.minecraft.world.gen.feature.template.Template.func_237141_a_(Template.java:358) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:structures.TemplateAccessor,pl:mixin:APP:lootr.mixins.json:MixinTemplate,pl:mixin:A}
at net.minecraft.util.math.shapes.VoxelShapePart.func_211541_a(SourceFile:313) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:VSPartAccess,pl:mixin:A}
at net.minecraft.util.math.shapes.VoxelShapePart.func_211540_a(SourceFile:283) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:VSPartAccess,pl:mixin:A}
at net.minecraft.world.gen.feature.template.Template.func_222857_a(Template.java:348) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:structures.TemplateAccessor,pl:mixin:APP:lootr.mixins.json:MixinTemplate,pl:mixin:A}
at net.minecraft.world.gen.feature.TreeFeature.func_241855_a(SourceFile:179) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:features.LessjungleBushInStructuresMixin,pl:mixin:A}
at net.minecraft.world.gen.feature.TreeFeature.func_241855_a(SourceFile:37) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:features.LessjungleBushInStructuresMixin,pl:mixin:A}
at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading,re:mixin}
at net.minecraft.world.gen.feature.ConfiguredRandomFeatureList.func_242787_a(SourceFile:31) ~[?:?] {re:classloading}
at net.minecraft.world.gen.feature.MultipleWithChanceRandomFeature.func_241855_a(SourceFile:20) ~[?:?] {re:classloading}
at net.minecraft.world.gen.feature.MultipleWithChanceRandomFeature.func_241855_a(SourceFile:11) ~[?:?] {re:classloading}
at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading,re:mixin}
at net.minecraft.world.gen.feature.DecoratedFeature.func_242772_a(SourceFile:23) ~[?:?] {re:classloading}

**Comment by bvierra** [comment]
Most likely an upstream issue so I also opened: https://github.com/Creators-of-Create/Create/issues/2393
