### ISSUE TITLE
Fresh install of v1.3 crashes on loading everytime

### ISSUE THREAD

**Issue by benten2000** [simibubi/Above-and-Beyond#331]
Downloaded the latest pack via MultiMC with it set to use Java 8 but as soon as I press play it crashes with this error.

https://pastebin.com/EbQ5JN7i

**Comment by Midlou** [comment]
Same crash here. Started after updating to Java (build 1.8.0_321-b07). I don't know if it's related.

**Comment by Dwerg** [comment]
Server wouldn't start after updating Java to update 321. Removed it and went back to update 311 again, server starts and everything is fine. The latest Java definitely broke something.

**Comment by qchronod** [comment]
Getting the same as above, heres the console when it doesn't run

```
C:\Minecraft\Servers\Create A&B>"C:\Program Files\Java\jre1.8.0_321\bin\java.exe" -Xmx8G -jar forge-1.16.5-36.2.20.jar nogui
2022-01-22 09:14:08,487 main WARN Advanced terminal features are not available in this environment
[09:14:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, mlserver, --fml.forgeVersion, 36.2.20, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[09:14:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_321 by Oracle Corporation
[09:14:09] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[09:14:09] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Minecraft/Servers/Create%20A&B/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[09:14:11] [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property 
Exception in thread "main" [09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.ClassLoader.loadClass(Unknown Source)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.Class.forName0(Native Method)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.Class.forName(Unknown Source)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.util.HashMap.forEach(Unknown Source)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[09:14:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)****
```

**Comment by BlueBird931** [comment]
I had the same issue, but after a few hours of failed attempts I managed to solve the issue.
Here's what ended up working for me:

I installed Java SE Development Kit 8u311 x64 (instead of the latest version 8u321) 

After that, instead of editing the environment variables to make the server start with Java 8 instead of Java 17, I manually specified the Java 8 directory in the .bat file used to start the server.

The .bat script should look something like this:
`"C:\Program Files\Java\jdk1.8.0_311\bin\java.exe" -Xmx8G -Xms8G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=0 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+UseG1GC -jar forge-1.16.5-36.2.20.jar nogui`

Hope this can help.

**Comment by qchronod** [comment]
The issue is that it's crashing with the newer Java 8u321. Something seems to have changed that is causing an uncaught exception error.

(Also it seems to be nearly impossible to download old versions from the normal java website, I had to go find one from a 3rd party site.)

**Comment by Dwerg** [comment]
> (Also it seems to be nearly impossible to download old versions from the normal java website, I had to go find one from a 3rd party site.)

For anyone else looking and wanting to avoid potential malware. An official download can be found in the Java archive here [here.](https://www.oracle.com/java/technologies/javase/javase8u211-later-archive-downloads.html) 
Scroll down to "Java SE Runtime Environment 8u311" and get the Windows x64 Installer. You'll need to log in or create an account (which is free), you don't need real information to create an account except the email address because of a verification email.

**Comment by HeWhoThreadsLightly** [comment]
Duplicate issues
https://github.com/simibubi/Above-and-Beyond/issues/135
https://github.com/simibubi/Above-and-Beyond/issues/169
https://github.com/simibubi/Above-and-Beyond/issues/172
https://github.com/simibubi/Above-and-Beyond/issues/331

**Comment by HeWhoThreadsLightly** [comment]
Java 9.0.1 worked for me. Already had it installed so i tried it while waiting for java 8 to download, maybe more versions work than 8 and 9.
