### ISSUE TITLE
IllegalAccessError on startup

### ISSUE THREAD

**Issue by tgraczyk** [simibubi/Above-and-Beyond#4]
Hello,

I'm currently getting the following exception upon starting the server. I've tried updating java and a fresh install of the server and I've had no luck trying to start the server. Any ideas?

Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x4de5031f) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x4de5031f
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)

**Comment by simibubi** [comment]
Hi,
this modpack runs best on Java 8 (1.8.x). I cannot see the version you are using, but switching to that would be my best guess

**Comment by tgraczyk** [comment]
I am currently using 1.8.0_311-b11 (Version 8 Update 311), I will double-check to make sure this is the only instance of java on my server PC
