### ISSUE TITLE
Error when running server start script.

### ISSUE THREAD

**Issue by jorlyg** [simibubi/Above-and-Beyond#41]
Tried to run the server start script from the github wiki page and got this error message, I have verified that I have Java version 8 and just did an update to be sure that it wasn't out of date. How do I get it to work?

2021-11-04 22:54:07,914 main WARN Advanced terminal features are not available in this environment
[22:54:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.8, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, -XX:+UseG1GC, -Xmx8G, -Xms8G, -Dsun.rmi.dgc.server.gcInterval=2147483646, -XX:+UnlockExperimentalVMOptions, -XX:G1NewSizePercent=20, -XX:G1ReservePercent=20, -XX:MaxGCPauseMillis=50, -XX:G1HeapRegionSize=32M]
[22:54:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 16.0.1 by Oracle Corporation
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x29f69090) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x29f69090
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)

**Comment by simibubi** [comment]
the log sais "starting: java version 16.0.1 by Oracle Corporation" 😄

**Comment by jorlyg** [comment]
> the log sais "starting: java version 16.0.1 by Oracle Corporation" 😄

In the Java control panel it says «Version 8 Update 311 (build 1.8.0_311-b11)» though.

**Comment by Trnrr** [comment]
> 
> 
> > the log sais "starting: java version 16.0.1 by Oracle Corporation" 😄
> 
> In the Java control panel it says «Version 8 Update 311 (build 1.8.0_311-b11)» though.

What does `java -version` say in the console?

**Comment by jorlyg** [comment]
> > > the log sais "starting: java version 16.0.1 by Oracle Corporation" 😄
> > 
> > 
> > In the Java control panel it says «Version 8 Update 311 (build 1.8.0_311-b11)» though.
> 
> What does `java -version` say in the console?
That one says 16.0.1...

java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

**Comment by jorlyg** [comment]
I have reinstalled Java 8 but it seems to try to use Java 16 still, is there a way to make it use Java 8 or will I have to delete Java 16 from the pc?

**Comment by jorlyg** [comment]
Fixed the path in Environment Variables for java 8 and the server worked.
