### ISSUE TITLE
Opening serverpack "forge-1.16.5-36.2.20.jar" does not launch. Need Help

### ISSUE THREAD

**Issue by Escavliar** [simibubi/Above-and-Beyond#521]
To provide some detail, I've been doing server hosting for a while now for my buddies, but exclusively for this modpack (serverpack) I proceed to do all the necessary steps to build it and and launch it.
 1) Download the serverpack.
 2) Extract the serverpack in folder/drive of my choice)
 3) Open extracted copy of folder and launch the installer and select the the same folder that the modpacks are located and click "Install server" 
4) (Successfully installs without errors) I then click the "Minecraft_Server.jar" to propagate all necessary file structure. 
5) Then I click the .jar file associated with the modpack and it's version, and that also propagates what I assume it needs to.
 6) I then open the EULA document and make "False", "True" *Save* and exit,
 7) Input java argument "java -Xmx8G -Xms8G -jar forge-1.16.5-36.2.20.jar nogui" to a "Run.bat" text document that I created (It does not provide me with one) and click run, and it proceeds to launch.

here's the but... only 2 seconds in, it crashes like clockwork every single time. I have no idea how to resolve this issue because I'm finding no one that has the same issue, probably because I have no log errors to run off of it to troubleshoot. If there ARE logs and I'm just dumb can someone help me find them, and if not... what's the next step? 

YES, I have clicked the .jar file associated with the modpack and "open with -> JavaTMPlatformSEBinary" (Java 8) and it proceeds to do nothing.

I've completed this process with over 20 different modpacks and have had a few issues, but none that I couldn't resolve and get working. As it stands, Any other modpack that I click the associated .jar file, opens the modpack server as expected just fine. It is only this one I'm having issues with.

![Screenshot 2023-03-07 120557](https://user-images.githubusercontent.com/36748437/223495841-b9c2b9b9-177d-4197-9a52-9530e56c96dc.png)

**Comment by D-a-r-n-o-l-d** [comment]
try running the bat file through powershell or command prompt and telling us what it says

**Comment by Antoine-Becquet** [comment]
there is my error for the same problem :
\Downloads\Above+and+Beyond-1.3-Server>java -Xmx8G -jar forge-1.16.5-36.2.20.jar nogui
2023-04-04 18:39:12,412 main WARN Advanced terminal features are not available in this environment
[18:39:12] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.20, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[18:39:12] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 20 by Oracle Corporation
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x75f32542) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x75f32542
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)

**Comment by D-a-r-n-o-l-d** [comment]
Try running the server with the arguments given in the install/update guide:

java -Xmx8G -Xms8G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=0 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+UseG1GC -jar forge-1.16.5-36.2.20.jar nogui

If your server gives you an error where java says the memory allocated is too much then add the -d64 argument, if this still doesn't work, check your java version.
hope this helps!

EDIT:
I just looked more closely at your forge server version, I don't know if this is the problem but had to update to forge version 1.16.5-36.2.34

also I use java version 1.8.0_351

keep in mind I'm not a developer, I'm  just a dude who got it working after a while.

**Comment by Antoine-Becquet** [comment]
> Try running the server with the arguments given in the install/update guide:
> 
> java -Xmx8G -Xms8G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=0 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+UseG1GC -jar forge-1.16.5-36.2.20.jar nogui
> 
> If your server gives you an error where java says the memory allocated is too much then add the -d64 argument, if this still doesn't work, check your java version. hope this helps!
> 
> EDIT: I just looked more closely at your forge server version, I don't know if this is the problem but had to update to forge version 1.16.5-36.2.34
> 
> also I use java version 1.8.0_351
> 
> keep in mind I'm not a developer, I'm just a dude who got it working after a while.

Doesnt work with any of the two versions of forge

**Comment by DrScienMath** [comment]
> there is my error for the same problem : \Downloads\Above+and+Beyond-1.3-Server>java -Xmx8G -jar forge-1.16.5-36.2.20.jar nogui 2023-04-04 18:39:12,412 main WARN Advanced terminal features are not available in this environment [18:39:12] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.20, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui] [18:39:12] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 20 by Oracle Corporation Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x75f32542) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x75f32542 at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41) at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95) at cpw.mods.modlauncher.SecureJarHandler.(SecureJarHandler.java:41) at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55) at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52) at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47) at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62) at cpw.mods.modlauncher.Launcher.(Launcher.java:55) at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)

I believe your problem is the version of Java that is being used. I have both Java 17 and Java 8 installed, and when trying to run the serverpack with Java 17 it gives an almost identical error. The server installation instructions does say to use Java 8.

**Comment by DrScienMath** [comment]
I also had the same problem of the server not starting but updating the Forge version to 36.3.34 in the server files fixed the problem.

My current working setup:
Create: Above and Beyond server files 1.3
forge-1.16.5-36.2.34
Java 8 version 1.8.0_361

**Comment by Antoine-Becquet** [comment]
Do you only have java or also use a specific version of JDK ? If yes, which one ? 
 
  Le lun., avr. 10, 2023 à 4:07, Tony ***@***.***> a écrit:   


I also had the same problem of the server not starting but updating the Forge version to 36.3.34 in the server files fixed the problem.

My current working setup:
Create: Above and Beyond server files 1.3
forge-1.16.5-36.2.34
Java 8 version 1.8.0_361

**Comment by Erym974** [comment]
Hello ! 

I had the same issues and i have found in this #472 

Simply switch your java version to 11.
