### ISSUE TITLE
Server not working, unsure about what the problem is.

### ISSUE THREAD

**Issue by jdc-asdf** [simibubi/Above-and-Beyond#546]
Tried creating a server, by following the guide in the wiki section. However it does not launch.
here is the latest.log: 

[28May2023 13:50:41.127] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.20, --fml.mcpV>[28May2023 13:50:41.130] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_362 by Private Build
[28May2023 13:50:41.367] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[28May2023 13:50:41.409] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/viktor/Downloads/server/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar >[28May2023 13:50:44.264] [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
[28May2023 13:50:44.342] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Ma>[28May2023 13:50:44.342] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[28May2023 13:50:44.342] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(Transf>[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.jav>[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.jav>[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at java.lang.Class.forName0(Native Method)
[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at java.lang.Class.forName(Class.java:348)
[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLa>[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinCo>[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorM>[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformMan>[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchP>[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchP>[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandl>[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at java.util.HashMap.forEach(HashMap.java:1290)
[28May2023 13:50:44.343] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:9>[28May2023 13:50:44.344] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[28May2023 13:50:44.344] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[28May2023 13:50:44.344] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[28May2023 13:50:44.344] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[28May2023 13:50:44.344] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[28May2023 13:50:44.344] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[28May2023 13:50:44.344] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:         at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)

**Comment by Tigger112** [comment]
same here

**Comment by kiskoza** [comment]
This is an issue with the Forge version and an incompatible (newer) java. The solution could be found here: https://github.com/simibubi/Above-and-Beyond/pull/489
