### ISSUE TITLE
Installing a private CAAB server

### ISSUE THREAD

**Issue by peisach** [simibubi/Above-and-Beyond#557]
My apologies if this is not the correct place to post this.

I am trying to install a new CAAB server on my home computer running Eclipse Adoptium java 8 on windows 11.  I am running into a problem getting the server to start.  Attached is the startup batch file that I am using and log file.

Any advice on how to proceed forward?

Thank you.

@ECHO OFF
set %JAVA_HOME%=C:\"Program Files"\Java\"Eclipse Adoptium"\jdk-8.0.372.7-hotspot
SETLOCAL

:MAIN
"C:\Program Files\Eclipse Adoptium\jdk-8.0.372.7-hotspot\bin\java.exe" -Xmx8G -Xms6G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=0 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+UseG1GC -jar forge-1.16.5-36.2.20.jar nogui
GOTO EOF

:EOF
pause

2023-06-29 11:53:47,531 main WARN Advanced terminal features are not available in this environment
[11:53:47] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.20, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[11:53:47] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_372 by Temurin
[11:53:47] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[11:53:47] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/Redux/Documents/Minecraft/Above%20and%20Beyond/Above+and+Beyond-1.3-Server/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[11:53:49] [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
Exception in thread "main" [11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at java.lang.Class.forName0(Native Method)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at java.lang.Class.forName(Class.java:348)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at java.util.HashMap.forEach(HashMap.java:1290)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[11:53:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
Press any key to continue . . .

**Comment by kiskoza** [comment]
Your java version is incompatible with the Forge version this modpack is using. See the details here: https://github.com/simibubi/Above-and-Beyond/pull/489

**Comment by peisach** [comment]
Thank you!

Daniel
