### ISSUE TITLE
The games crashes after a few secconds 

### ISSUE THREAD

**Issue by Pikagusxd** [simibubi/Above-and-Beyond#561]
hi, i'm tryna play thi, but after a few seconds of playing it closes
[latest.log](https://github.com/simibubi/Above-and-Beyond/files/12004065/latest.log)

**Comment by RanPix** [comment]
i also have the same issue

**Comment by Avangardum** [comment]
I have the same issue when trying to launch the server pack using the "java -jar forge-1.16.5-36.2.20.jar nogui" command. It outputs the following text and crashes. Client installed via the CurseForge app works OK.
`
2023-07-15 18:37:48,044 main WARN Advanced terminal features are not available in this environment
[18:37:48] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.20, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[18:37:48] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_371 by Oracle Corporation
[18:37:49] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[18:37:49] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/Yuriy/Above%20and%20Beyond%201.3%20Server/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[18:37:51] [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
Exception in thread "main" [18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.ClassLoader.loadClass(Unknown Source)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.Class.forName0(Native Method)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.Class.forName(Unknown Source)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.util.HashMap.forEach(Unknown Source)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[18:37:51] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
`

**Comment by fiftycthulhu** [comment]
Me too, here's my crash file.
https://mclo.gs/JcSt2fy

**Comment by williamtorres64** [comment]
Me too
Log: https://mclo.gs/AsCJEMZ
Steps:
Add instance, CurseForge tab, search for "Create: Above and Beyond", and install the first result
Manually add the blocked mods SpawnerFix and Dice
Set Java version to 1.8
Launch
Get the error from the provided log

**Comment by william64644** [comment]
> 

I would set the title to:
Mixin config antiqueatlas.mixins.json does not specify "minVersion"
This could take a bit more attention from the developers

**Comment by williamtorres64** [comment]
Guys, this is a problem with the prism launcher, not the modpack, switching to [atlauncher](https://atlauncher.com/) solves it

**Comment by josemoncab** [comment]
The problem is not the Prism launcher but the java version. Use the java 8 u51 and works fine.

It works with the atlauncher by default because the launcher use the java version that comes with minecraft (atm call "jre-legacy" and its located in the installation path inside runtime folder) but if you download the same version manually and configure your launcher with them, works with any launcher I assume

**Comment by williamtorres64** [comment]
You see, that's why I love the open-source community 
# 🙂

**Comment by ananthashesha3000** [comment]
@josemoncab Where can java 8u51 be downloaded, tough, and is it the only version that can fix this issue?

**Comment by josemoncab** [comment]
In the official oracle page but you probably need to create an account

[https://www.oracle.com/es/java/technologies/javase/javase8-archive-downloads.html](https://www.oracle.com/es/java/technologies/javase/javase8-archive-downloads.html)

Search for the version 51

Not the server version!!

**Comment by ananthashesha3000** [comment]
@josemoncab It says this: [https://paste.ee/p/Jj6sj](https://paste.ee/p/Jj6sj)

**Comment by josemoncab** [comment]
You need to install it first

**Comment by ananthashesha3000** [comment]
@josemoncab Thanks! I'm a dumbass sometimes, and I knew Java had to be installed before, so I'm not sure why I didn't do it first here...
Also, out of curiosity, is there any way to find out what Java versions to use for specific modpacks?

Anyway, I hope whoever reads this (other than myself and @josemoncab) can use this to fix their instances.
