### ISSUE TITLE
Server Pack Doesnt run

### ISSUE THREAD

**Issue by TunedW0lf** [simibubi/Above-and-Beyond#582]
EDIT: got it to work by installing an old version of java (jdk8u312-b07 from https://adoptium.net/temurin/archive/?version=8) and updating the forge to version 36.2.34 BUT i cant assign more than a gigabyte of ram to the server for some reason

I run the forge-1.16.5-36.2.20.jar With the java -Xmx8G -Xms8G -jar forge-1.16.5-36.2.20.jar nogui args but it just gives me

2023-10-20 22:21:07,390 main WARN Advanced terminal features are not available in this environment
[22:21:07] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.20, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[22:21:07] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 20.0.2 by Oracle Corporation
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x3901d134) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x3901d134
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)

error what can i do to make it run
btw this is the server installation folder:
![image](https://github.com/simibubi/Above-and-Beyond/assets/142911798/eb6021a7-7ae9-46a1-9a00-7519cb81d8a7)

**Comment by Techdinosaur** [comment]
i am having the same issue have you resolved it ?

**Comment by TunedW0lf** [comment]
> i am having the same issue have you resolved it ?

Yes! I did Just download the java version that i wrote about on the edit

**Comment by glektarssza** [comment]
For the "cannot assign more than 1 GB" issue can you post the output of running `java -version`? I suspect you might have a 32-bit version of Java.
