### ISSUE TITLE
Modpack Failing to Launch

### ISSUE THREAD

**Issue by abculatter2** [simibubi/Above-and-Beyond#593]
I downloaded the pack using PolyMC, and it successfully boots Minecraft up to "FML early loading phase". However, several seconds in, it crashes. I pasted the PolyMC crash log here, as I'm really not sure what else to do at this point:

PolyMC version: 5.1

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.32.230.105, 13.32.230.112, 13.32.230.30, 13.32.230.62]

session.minecraft.net resolves to:
    [13.107.246.41, 13.107.213.41]

textures.minecraft.net resolves to:
    [13.107.246.41, 13.107.213.41]

api.mojang.com resolves to:
    [13.107.246.41, 13.107.213.41]

Minecraft folder is:
C:/Users/Sundry/AppData/Roaming/PolyMC/instances/Create- Above and Beyond/minecraft

Java path is:
C:/Program Files/Eclipse Adoptium/jre-8.0.362.9-hotspot/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_362, using 64 (amd64) architecture, from Temurin.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/Sundry/AppData/Roaming/PolyMC/instances/Create- Above and Beyond/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc2/ForgeWrapper-mmc2.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/net/minecraftforge/forge/1.16.5-36.2.20/forge-1.16.5-36.2.20-launcher.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔] abnormals_core-1.16.5-3.3.0
  [✔] AdvancedRocketry-1.16.5-2.0.0-12-universal
  [✔] AI-Improvements-1.16.2-0.3.0
  [✔] antiqueatlas-6.0.1-forge-mc1.16.5
  [✔] appleskin-forge-mc1.16.x-2.2.0
  [✔] appliedenergistics2-8.4.4
  [✔] Aquaculture-1.16.5-2.1.21
  [✔] archers_paradox-1.16.5-1.4.0.1
  [✔] Architects-Palette-1.16.4-1.1.4
  [✔] architectury-1.24.35-forge
  [✔] BackTools-1.16.5-10.1.0
  [✔] BetterAdvancements-1.16.5-0.1.0.108
  [✔] BetterBurning-1.16.5-6.0.6
  [✔] BiomesOPlenty-1.16.5-13.1.0.482-universal
  [✔] Buddycards-1.16.5-2.5.2
  [✔] bwncr-1.16.5-3.10.16
  [✔] catalogue-1.5.0-1.16.5
  [✔] cavebiomeapi-1.16.5-1.3.7
  [✔] CBMultipart-1.16.5-3.0.3.122-universal
  [✔] cc-tweaked-1.16.5-1.99.1
  [✔] Chisel-MC1.16.5-2.0.1-alpha.4
  [✔] chiselsandbits-1.0.43
  [✔] Chunk Pregenerator-V1.16-3.2.0
  [✔] ChunkNoGoByeBye-1.16.5-1.3.0
  [✔] cloth-config-4.12.41-forge
  [✔] Clumps-6.0.0.27
  [✔] cobblegenrandomizer-1.16-5.1.2
  [✔] CodeChickenLib-1.16.5-4.0.5.438-universal
  [✔] cofh_core-1.16.5-1.4.0.6
  [✔] configured-1.5.1-1.16.5
  [✔] connectivity-2.4-1.16.5
  [✔] constructionwand-1.16.5-2.6
  [✔] Controlling-7.0.0.28
  [✔] cookiecore-1.16.5-3.3.0-12106d2
  [✔] corpse-1.16.5-1.0.6
  [✔] CosmeticArmorReworked-1.16.5-v4a
  [✔] CraftingTweaks_1.16.5-12.2.1
  [✔] crashutilities-3.12
  [✔] create-mc1.16.5_v0.3.2g
  [✔] CTM-MC1.16.1-1.1.2.6
  [✔] culinaryconstruct-forge-1.16.5-4.0.0.6
  [✔] curios-forge-1.16.5-4.0.5.3
  [✔] darkerdepths-1.16.5-1.1.4
  [✔] decorative_blocks_abnormals-1.2
  [✔] decorative_blocks-1.16.4-1.7.2
  [✔] DefaultOptions_1.16.5-12.2.1
  [✔] Desolation 1.1.0-2 1.16.5
  [✔] Dice-1.16.5-1.2.0
  [✔] drinkbeer-1.16.5-2.3.5
  [✔] DungeonCrawl-1.16.5-2.3.2
  [✔] enchantedbookredesign-3.3-1.16.4
  [✔] endergetic-1.16.4-3.0.0
  [✔] EnderStorage-1.16.5-2.8.0.168-universal
  [✔] Exchangers-1.16.5-3.0.2
  [✔] exoticbirds-1.16.4-1.3.0
  [✔] extcaves-2.4
  [✔] fairylights-4.0.5-1.16.5
  [✔] FarmersDelight-1.16.5-0.5.3
  [✔] fastfurnaceminusreplacement-1.1-1.16.3
  [✔] FastLeafDecay-v25
  [✔] FastWorkbench-1.16.4-4.5.1
  [✔] ferritecore-2.1.0-forge
  [✔] flywheel-1.16-0.2.5
  [✔] forbidden_arcanus-16.2.2
  [✔] ftb-backups-2.1.2.2
  [✔] ftb-chunks-forge-1605.3.2-build.83
  [✔] ftb-library-forge-1605.3.4-build.90
  [✔] ftb-quests-forge-1605.3.5-build.72
  [✔] ftb-teams-forge-1605.2.3-build.40
  [✔] grapplemod-1.16.5-v12
  [✔] GunpowderLib-1.16.5-1.2.2
  [✔] iChunUtil-1.16.5-10.5.0
  [✔] ImprovedBackpacks-1.6.2.0
  [✔] inventorysorter-1.16.1-18.1.0
  [✔] item-filters-forge-1605.2.5-build.9
  [✔] Jade-1.16.4-2.8.0
  [✔] jei-1.16.5-7.7.1.137
  [✔] kubejs-create-1605.1.2-build.7
  [✔] kubejs-forge-1605.3.19-build.229
  [✔] kubejs-thermal-1605.1.4-build.3
  [✔] LibVulpes-1.16.5-1.0.2-25-universal
  [✔] lootr-1.16.5-0.0.9.30
  [✔] magicfeather-1.16.2-3.2.0
  [✔] Mantle-1.16.5-1.6.147
  [✔] metalbarrels-1.16.2-3.3b
  [✔] mightyarchitect-mc1.16.3_v0.5
  [✔] moreminecarts-1.3.12
  [✔] MoreObservers-1.4.1-MC1.16-Forge
  [✔] Morpheus-1.16.5-4.2.70
  [✔] MouseTweaks-2.14-mc1.16.2
  [✔] NaturesCompass-1.16.5-1.9.1-forge
  [✔] nolakes-0.1-1.16.4
  [✔] occultism-1.16.5-1.20.1
  [✔] OpenLoader-1.16.5-9.0.3
  [✔] orcinusscaves-1.3
  [✔] OreTweaker-1.16.5-2.6.0
  [✔] paintings-1.16.4-7.0.0.1
  [✔] Patchouli-1.16.4-53.2
  [✔] PathToDirt-1.2.0-mc1.16.x
  [✔] pipez-1.16.5-1.2.13
  [✔] Placebo-1.16.5-4.6.0
  [✔] ponderjs-1.16.5-1.0.3d
  [✔] portable_stonecutter-1.16.5-1.3.5
  [✔] portality-1.16.5-3.2.5
  [✔] PrettyPipes-1.9.5
  [✔] ProjectRed-1.16.5-4.11.0-beta-6-core
  [✔] ProjectRed-1.16.5-4.11.0-beta-6-illumination
  [✔] ProjectRed-1.16.5-4.11.0-beta-6-integration
  [✔] ProjectRed-1.16.5-4.11.0-beta-6-transmission
  [✔] randomium-1.16.5-1.7
  [✔] ravencoffee-1.16.5-beta_01
  [✔] reliquary-1.16.5-1.3.5.1100
  [✔] repurposed_structures_forge-3.4.4+1.16.5
  [✔] rhino-forge-1605.1.5-build.75
  [✔] Rubber_Duck-1.16.5-1.2.0
  [✔] Scorge-3.1.3
  [✔] selene-1.16.5-1.9.0
  [✔] shutupexperimentalsettings-1.0.3
  [✔] SoundFilters-0.14_for_1.16.2
  [✔] spark-forge
  [✔] SpawnerFix-1.16.2-1.0.0.2
  [✔] StorageDrawers-1.16.3-8.3.0
  [✔] strawgolem-1.16-1.9
  [✔] structurescompass-1.16.5-1.2.0
  [✔] supplementaries-1.16.5-0.17.12b
  [✔] TConstruct-1.16.5-3.3.0.308
  [✔] thermal_expansion-1.16.5-1.4.1.3
  [✔] thermal_foundation-1.16.5-1.4.1.7
  [✔] thermal_innovation-1.16.5-1.4.1.3
  [✔] thermal_locomotion-1.16.5-1.4.1.2
  [✔] titanium-1.16.5-3.2.8.7-22
  [✔] torchmaster-2.3.8
  [✔] valhelsia_core-16.0.13a
  [✔] WaterStrainer-1.16.3-10.0.0
  [✔] worldshape-1.0
  [✔] xkdeco_0.2.4

Params:
  --username  --version 1.16.5 --gameDir C:/Users/Sundry/AppData/Roaming/PolyMC/instances/Create- Above and Beyond/minecraft --assetsDir C:/Users/Sundry/AppData/Roaming/PolyMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.20 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx7168m, -Duser.language=en]

Minecraft process ID: 11172

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2023-12-17 20:28:41,121 main WARN Advanced terminal features are not available in this environment
[20:28:41] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, abculatter_2, --version, 1.16.5, --gameDir, C:/Users/Sundry/AppData/Roaming/PolyMC/instances/Create- Above and Beyond/minecraft, --assetsDir, C:/Users/Sundry/AppData/Roaming/PolyMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.20, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[20:28:41] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_362 by Temurin
[20:28:41] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[20:28:41] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/Sundry/AppData/Roaming/PolyMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[20:28:46] [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
Dec 17, 2023 8:28:46 PM org.polymc.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	... 9 more
Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
	at java.util.HashMap.forEach(HashMap.java:1290)
	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	... 14 more
Dec 17, 2023 8:28:46 PM org.polymc.EntryPoint main
INFO: Exiting with 1
Process exited with code 1.
Clipboard copy at: 17 Dec 2023 20:29:00 -0500

**Comment by DavidDGTNT** [comment]
Same issue here, loading from Prism Launcher (Basically better PolyMC, [see here](https://prismlauncher.org/wiki/overview/faq/#what-happened-to-polymc-why-is-there-a-new-fork))

**Comment by AwesomeKalin** [comment]
Not a bug, see [https://github.com/McModLauncher/modlauncher/issues/91](https://github.com/McModLauncher/modlauncher/issues/91)

**Comment by benjamin051000** [comment]
Looks like this is a workaround: https://github.com/McModLauncher/modlauncher/issues/91#issuecomment-1058754244

I'm able to get past this error and get to the title screen after upgrading the forge version.
