### ISSUE TITLE
Server Crashes on startup

### ISSUE THREAD

**Issue by SteseDav** [simibubi/Above-and-Beyond#610]
Following the instructions here :- https://github.com/simibubi/Above-and-Beyond/wiki

the jar crashes within seconds of starting. 

```
E:\Java\Above and Beyond-1.3-Server>E:\jre\java8\bin\java.exe -Xmx8G -Xms8G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=0 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+UseG1GC -jar forge-1.16.5-36.2.20.jar nogui
2024-08-08 17:09:30,755 main WARN Advanced terminal features are not available in this environment
[17:09:30] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.20, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[17:09:30] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_422-422 by OpenLogic-OpenJDK
[17:09:35] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[17:09:35] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/E:/Java/Above%20and%20Beyond-1.3-Server/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[17:09:37] [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
Exception in thread "main" [17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at java.lang.Class.forName0(Native Method)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at java.lang.Class.forName(Class.java:348)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at java.util.HashMap.forEach(HashMap.java:1290)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[17:09:37] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:       at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)

E:\Java\Above and Beyond-1.3-Server>pause
```
Any ideas? Is there an updated server guide?

**Comment by noahcoolboy** [comment]
Forge 1.16.5 has some issues with recent Java 8 releases
Try downgrading to java 8.0.312
https://github.com/adoptium/temurin8-binaries/releases/tag/jdk8u312-b07

**Comment by Lovinoes** [comment]
> Forge 1.16.5 has some issues with recent Java 8 releases Try downgrading to java 8.0.312 https://github.com/adoptium/temurin8-binaries/releases/tag/jdk8u312-b07

upgrading forge works too.
