### ISSUE TITLE
Game Crashes during loading

### ISSUE THREAD

**Issue by T3RR5V0N** [simibubi/Above-and-Beyond#612]
When loading the modpack, I get this error. I'm running it through the Prism Launcher on Arch Linux.

```
[10:43:32] [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
	at java.util.HashMap.forEach(HashMap.java:1290)
	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	... 8 more
Exiting with ERROR
Process exited with code 2.
```

**Comment by ghost** [comment]
Same issue with same environment (OpenJDK 1.8.0_422). Fixed by fresh install on ATLauncher.

**Comment by Exploctopus** [comment]
I experienced the same issue. 
Ran through Prism Launcher on Windows 11.
I received a very similar error message.
On further investigation it seems to be related to Java 8 versions post 1.8.0_321 being incompatible with the mod pack.
See [This issue](https://github.com/McModLauncher/modlauncher/issues/91)
After swapping to version 1.8.0_312, that can be found on the Adoptium projects webpage ( [Here](https://adoptium.net/?variant=openjdk8&jvmVariant=hotspot) ) the game launched successfully.

**Comment by ghost** [comment]
Thanks you very much! Solved by downgrade OpenJDK.

```console
pacman -U https://archive.archlinux.org/packages/j/jdk8-openjdk/jdk8-openjdk-8.u312-2-x86_64.pkg.tar.zst \
  https://archive.archlinux.org/packages/j/jre8-openjdk/jre8-openjdk-8.u312-2-x86_64.pkg.tar.zst \
  https://archive.archlinux.org/packages/j/jre8-openjdk-headless/jre8-openjdk-headless-8.u312-2-x86_64.pkg.tar.zst
```
